version: "3.9"

services:
  react:
    container_name: ADEPT-ML-Frontend
    restart: always
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    container_name: ADEPT-ML-Backend
    restart: always
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - "8000:80"
  data-management:
    container_name: ADEPT-ML-Data-Management
    restart: always
    build:
      context: ./Data-Management
      dockerfile: Dockerfile
    volumes:
      - ./Data-Management:/app
      - ./data:/data
    ports:
      - "8001:80"
  preprocessing:
    container_name: ADEPT-ML-Preprocessing
    restart: always
    build:
      context: ./Preprocessing
      dockerfile: Dockerfile
    volumes:
      - ./Preprocessing:/app
    ports:
      - "8002:80"
  feature-engineering:
    container_name: ADEPT-ML-Feature-Engineering
    restart: always
    build:
      context: ./Feature-Engineering
      dockerfile: Dockerfile
    volumes:
      - ./Feature-Engineering:/app
    ports:
      - "8003:80"
  anomaly-detection:
    container_name: ADEPT-ML-Anomaly-Detection
    restart: always
    build:
      context: ./Anomaly-Detection
      dockerfile: Dockerfile
    volumes:
      - ./Anomaly-Detection:/app
    ports:
      - "8004:80"
  explainability:
    container_name: ADEPT-ML-Explainability
    restart: always
    build:
      context: ./Explainability
      dockerfile: Dockerfile
    volumes:
      - ./Explainability:/app
    ports:
      - "8005:80"
