version: "3.9"

services:
  react:
    container_name: ADEPT-ML-Frontend
    restart: always
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/src:/app/src
    ports:
      - "80:1234"
    command: npx parcel ./src/index.html
  backend:
    container_name: ADEPT-ML-Backend
    restart: always
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - "8000:80"
  data-management:
    container_name: ADEPT-ML-Data-Management
    restart: always
    build:
      context: ./Data-Management
      dockerfile: Dockerfile
    volumes:
      - ./Data-Management:/app
      - ./data:/app/data
    ports:
      - "8001:80"
  anomaly-detection:
    container_name: ADEPT-ML-Anomaly-Detection
    restart: always
    build:
      context: ./Anomaly-Detection
      dockerfile: Dockerfile
    volumes:
      - ./Anomaly-Detection:/app
    ports:
      - "8004:80"
